apiVersion: platform.confluent.io/v1beta1
kind: Connect
metadata:
  name: connect
spec:


  metrics:
    prometheus:
      whitelist:
        - kafka.connect:type=app-info,client-id=*
        - kafka.connect:type=connect-worker-rebalance-metrics
        - kafka.connect:type=connect-coordinator-metrics,*
        - kafka.connect:type=connect-metrics,*
        - kafka.connect:type=connect-worker-metrics
        - kafka.connect:type=connect-worker-metrics,*
        - kafka.connect:type=connector-metrics,*
        - kafka.connect:type=*-task-metrics,*
        - kafka.connect:type=task-error-metrics,*
        - confluent.replicator:type=confluent-replicator-task-metrics,*
        - kafka.connect.oracle.cdc:type=source-task-metrics,*
        - kafka.consumer:type=consumer-fetch-manager-metrics,*
        - debezium.oracle:type=connector-metrics,*
        - kafka.consumer:*
        - kafka.producer:*
      blacklist:
        - kafka.admin.client:*
        - kafka.producer:client-id=confluent.monitoring*,*
        - kafka.*:type=kafka-metrics-count,*
      rules:
        - labels:
            $2: $3
            client-id: $1
          name: kafka_connect_app_info
          pattern: 'kafka.connect<type=app-info, client-id=(.+)><>(.+): (.+)'
          type: UNTYPED
          value: "1"
          valueFactor: 1
        - name: kafka_connect_connect_worker_rebalance_metrics_$1
          pattern: kafka.connect<type=connect-worker-rebalance-metrics><>([^:]+)
          valueFactor: 1
        - labels:
            client_id: $2
          name: kafka_connect_$1_$3
          pattern: kafka.connect<type=(.+), client-id=(.+)><>([^:]+)
          valueFactor: 1
        - labels:
            connector: aggregate
          name: kafka_connect_connect_worker_metrics_$1
          pattern: kafka.connect<type=connect-worker-metrics><>([^:]+)
          valueFactor: 1
        - labels:
            connector: $1
          name: kafka_connect_connect_worker_metrics_$2
          pattern: kafka.connect<type=connect-worker-metrics, connector=(.+)><>([^:]+)
          valueFactor: 1
        - labels:
            $2: $3
            connector: $1
          name: kafka_connect_connector_metrics
          pattern: 'kafka.connect<type=connector-metrics, connector=(.+)><>(.+): (.+)'
          type: UNTYPED
          value: "1"
          valueFactor: 1
        - labels:
            connector: $2
            task: $3
          name: kafka_connect_$1_task_metrics_$4
          pattern: 'kafka.connect<type=(.+)-task-metrics, connector=(.+), task=(\d+)><>(.+):
              (.+)'
          valueFactor: 1
        - labels:
            connector: $1
            task: $2
          name: kafka_connect_task_error_metrics_$3
          pattern: kafka.connect<type=task-error-metrics, connector=(.+), task=(\d+)><>([^:]+)
          valueFactor: 1
        - labels:
            $1: $2
            $3: $4
            $5: $6
            $7: $8
          name: confluent_replicator_task_metrics_$9
          pattern: 'confluent.replicator<type=confluent-replicator-task-metrics, confluent-replicator-(.*)=(.+),
              confluent-replicator-(.+)=(.+), confluent-replicator-(.+)=(.+), confluent-replicator-(.+)=(.+)><>confluent-replicator-task-topic-partition-(.*):
              (.*)'
          valueFactor: 1
        - labels:
            $1: $2
            $3: $4
            $5: $6
            $7: $8
            $9: $10
          name: confluent_replicator_task_metrics_info
          pattern: 'confluent.replicator<type=confluent-replicator-task-metrics, confluent-replicator-(.*)=(.+),
              confluent-replicator-(.+)=(.+), confluent-replicator-(.+)=(.+), confluent-replicator-(.+)=(.+)><>(confluent-replicator-destination-cluster|confluent-replicator-source-cluster|confluent-replicator-destination-topic-name):
              (.*)'
          value: "1"
          valueFactor: 1
        - labels:
            $3: $4
            client_id: $2
            client_type: $1
          name: kafka_$1_app_info
          pattern: 'kafka.(.+)<type=app-info, client-id=(.+)><>(.+): (.+)'
          type: UNTYPED
          value: "1"
          valueFactor: 1
        - labels:
            $3: $4
            $5: $6
            $7: $8
            client_type: $1
          name: kafka_$1_$2_$9
          pattern: 'kafka.(.+)<type=(.+), (.+)=(.+), (.+)=(.+), (.+)=(.+)><>(.+):'
          type: GAUGE
          valueFactor: 1
        - labels:
            $3: $4
            $5: $6
            client_type: $1
          name: kafka_$1_$2_$7
          pattern: 'kafka.(.+)<type=(.+), (.+)=(.+), (.+)=(.+)><>(.+):'
          type: GAUGE
          valueFactor: 1
        - labels:
            $3: $4
            client_type: $1
          name: kafka_$1_$2_$5
          pattern: 'kafka.(.+)<type=(.+), (.+)=(.+)><>(.+):'
          type: GAUGE
          valueFactor: 1
        - labels:
            client_type: $1
          name: kafka_$1_$2_$3
          pattern: 'kafka.(.+)<type=(.+)><>(.+):'
          valueFactor: 1
